### ISSUE TITLE
Listening on port

### ISSUE THREAD

**Issue by da-na** [IBM-Swift/Kitura-net#9] opened 2016-03-14 19:32 UTC
Hi!
I wanted to replicate the Kitura-TodoList project with my own classes. I've modified the provided ones and now after my new project succesfully compiles, whenever I type in browser: `http://localhost:8090/messages` in the browser I see: `Cannot GET /messages.` and in the terminal I see `INFO: spiListen(_:port:) (...)/Packages/Kitura-net-0.4.0/Sources/KituraNet/HttpServerSpi.swift line 51 - Accepted connection from: 127.0.0.1on port 36054 
UnexpectedEOF`

Why would the server accept connection on port 36054 if I explicitly try to connect on 8090? Or maybe I'm doing sth wrong?
Any help will be appreciated!
Thanks :)

**Comment by dfirsht** [comment] 2016-03-15 15:02
Duplicate of #10

**Closed by dfirsht** 2016-03-15 15:02 UTC
